[package]
name = "hellorust"
version = "0.0.1"
edition = "2021"

[lib]
name = "hellorust"
crate-type = ["cdylib"]

[dependencies]
jni = { version = "0.19.0", default-features = false }

[build-dependencies]
cbindgen = "0.24.3"