[package]
name = "hellorust-native"
version = "0.0.1"
edition = "2021"

[lib]
name = "hellorust"
crate-type = ["cdylib"]

[dependencies]
hellorust_core = { path = "../hellorust" }

[build-dependencies]
cbindgen = "0.24.3"